#!/usr/bin/env bash
############################################################
declare   "key=nature,animals"
declare   "url=https://source.unsplash.com/${MODE}/?${key}"
declare   "path=org.gnome.desktop.background picture-uri"
declare   "img=/etc/skel/Picture/_.jpg"
############################################################
source    "net2.sh"  "${img}"  "${url}"  "${img}"
############################################################
eval      "feh --bg-fill --no-fehbg ${img}"
eval      "gsettings set ${path} ${img}"
############################################################
